# -*- coding: utf-8 -*-
"""Copy of Snippets: Importing libraries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SiOT9Auide-S4lAe7OAP7zyV9bOUnZAw

# Importing a library that is not in Colaboratory

To import a library that's not in Colaboratory by default, you can use `!pip install` or `!apt-get install`.
"""

pip install matplotlib seaborn

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Sample data (similar to the Instagram dataset)
data = {
    "Follower Name": ["John Doe", "Jane Smith", "Emily Clark", "Michael Lee", "Sara Johnson"],
    "Country": ["USA", "India", "UK", "Canada", "Brazil"],
    "Age": [25, 30, 22, 28, 35],
    "Gender": ["Male", "Female", "Female", "Male", "Female"],
    "Account Created Year": [2018, 2015, 2020, 2016, 2019],
    "Time Spent (minutes)": [120, 150, 90, 180, 200]
}

# Create DataFrame
df = pd.DataFrame(data)

# 1. Bar Plot: Followers by Country
plt.figure(figsize=(8, 5))
sns.countplot(x="Country", data=df, palette="Blues_d")
plt.title('Followers by Country')
plt.xlabel('Country')
plt.ylabel('Number of Followers')
plt.show()

# 2. Histogram: Distribution of Time Spent (minutes)
plt.figure(figsize=(8, 5))
sns.histplot(df['Time Spent (minutes)'], bins=5, kde=True, color='purple')
plt.title('Distribution of Time Spent on Instagram')
plt.xlabel('Time Spent (minutes)')
plt.ylabel('Frequency')
plt.show()

# 3. Box Plot: Time Spent by Gender
plt.figure(figsize=(8, 5))
sns.boxplot(x="Gender", y="Time Spent (minutes)", data=df, palette="Set2")
plt.title('Time Spent on Instagram by Gender')
plt.xlabel('Gender')
plt.ylabel('Time Spent (minutes)')
plt.show()

!pip install matplotlib-venn

!apt-get -qq install -y libfluidsynth1

"""# Install 7zip reader [libarchive](https://pypi.python.org/pypi/libarchive)"""

# https://pypi.python.org/pypi/libarchive
!apt-get -qq install -y libarchive-dev && pip install -U libarchive
import libarchive

"""# Install GraphViz & [PyDot](https://pypi.python.org/pypi/pydot)"""

# https://pypi.python.org/pypi/pydot
!apt-get -qq install -y graphviz && pip install pydot
import pydot

"""# Install [cartopy](http://scitools.org.uk/cartopy/docs/latest/)"""

!pip install cartopy
import cartopy